### PR TITLE
#5 - Passing attributes to web component

### PR DESCRIPTION
**Pull request by estruyf**
Includes a fix to pass all properties/attributes to the web component.

### CODE REVIEW

**Comment by estruyf** [comment]
This changes fixes it, but makes something else fail.

**Comment by estruyf** [comment]
This change should work better.

**Review by nmetulev — APPROVED** [review]

**Comment by nmetulev** [comment]
Sorry, I missed this PR. Thanks for the fix and apologies for ignoring you

**Comment by estruyf** [comment]
No worries @nmetulev, now I can remove my custom fork and start using your version again 😉

**Pull request merged**
